import './globals.css'
import type { Metadata } from 'next'
import Nav from './auth/Nav'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import QueryWrapper from './components/queryWrapper'

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-roboto',
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head />
			<body
				className={`mx-4 md:mx-48 xl:mx-96 ${roboto.variable} bg-gray-200`}
			>
				<QueryWrapper>
					<Nav />
					{children}
				</QueryWrapper>
			</body>
		</html>
	)
}
